// convention : variable name and variable variable should be same
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_MOBILE = 'UPDATE_MOBILE';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_OTP = 'UPDATE_OTP';
export const UPDATE_PASSCODE = 'UPDATE_PASSCODE';
export const UPDATE_GENDER = 'UPDATE_GENDER';
export const UPDATE_DOB = 'UPDATE_DOB';
export const UPDATE_GOOGLE_USER_IMAGE = 'UPDATE_GOOGLE_USER_IMAGE';
export const UPDATE_GOOGLETOKEN = 'UPDATE_GOOGLETOKEN';
export const UPDATE_FETCHED_URL = 'UPDATE_FETCHED_URL';
export const UPDATE_HEIGHT = 'UPDATE_HEIGHT';
export const UPDATE_WEIGHT = 'UPDATE_WEIGHT';
export const UPDATE_TEMPHEIGHT = 'UPDATE_TEMPHEIGHT';
export const UPDATE_TEMPWEIGHT = 'UPDATE_TEMPWEIGHT';
export const UPDATE_BMI = 'UPDATE_BMI';
export const UPDATE_INVITECODE = 'UPDATE_INVITECODE';
export const UPDATE_TEMPDOB = 'UPDATE_TEMPDOB';
export const UPDATE_IMAGE_DETAILS = 'UPDATE_IMAGE_DETAILS';

/* ASSESSMENT REDUCER ACTION TYPES */
export const UPDATE_ASSESSMENT_THEME = 'UPDATE_ASSESSMENT_THEME';
export const EXIT_ASSESSMENT = 'EXIT_ASSESSMENT';
export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
export const UPDATE_CURRENTQUESTION = 'UPDATE_CURRENTQUESTION';
export const IS_NEXT_QUESTION_LOADING = 'IS_NEXT_QUESTION_LOADING';
export const UPDATE_CURRENTASSESSMENT = 'UPDATE_CURRENTASSESSMENT';
export const UPDATE_ASSESSMENTDETAILS = 'UPDATE_ASSESSMENTDETAILS';
export const UPDATE_ASSESSMENT_ID = 'UPDATE_ASSESSMENT_ID';
export const UPDATE_CURRENT_FLOW = 'UPDATE_CURRENT_FLOW';
export const UPDATE_CURRENT_ANSWER = 'UPDATE_CURRENT_ANSWER';

/* ASSESSMENT LIST REDUCER ACTION TYPES */
export const UPDATE_ASSESSMENTSLIST = 'UPDATE_ASSESSMENTSLIST';

/* ASSESSMENT REPORT REDUCER ACTION TYPES */
export const UPDATE_ASSESSMENT_REPORT = 'UPDATE_ASSESSMENT_REPORT';

export const RESET_STATE = 'RESET_STATE';

/* GOALS LIST REDUCER ACTION TYPES */
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_DURATION = 'UPDATE_DURATION';
export const UPDATE_HOURS_LEFT = 'UPDATE_HOURS_LEFT';
